replicaCount: 1

# image:
#   repository: hub.docker.com/yaleits/cost-api

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
  rules:
    - paths: ['/v1/cost', '/v1/metrics', '/v1/inventory']

probePath: '/v1/cost/ping'
