name: Docker Image CI

on:
  release:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag yaleits/costapi
        --build-arg version=${{ github.ref }} --build-arg githash=${{ github.sha }}
        --build-arg buildstamp=$(date +%s)
